name: libc
version: 0.0.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: The C standard library wrapper (currently only header files) for the "binary interop" and "binary types".
homepage: https://github.com/mezoni/libc
dependencies:
  binary_interop: any
dev_dependencies:
  unittest: any
